#!/bin/sh

if [ -z "$USER" ]; then
  echo "\$USER env var is required"
  exit 1
fi
if [ -z "$PASSWORD" ]; then
  echo "\$PASSWORD env var is required"
  exit 1
fi

if [ -z "$DEST" ]; then
  echo "\$DEST env var is required"
  exit 1
fi

NPROC=${NPROC:-'-1'}

zcash-fetch-params
echo 'gen=1' > ~/.zcash/zcash.conf
echo "genproclimit=$NPROC" >> ~/.zcash/zcash.conf
echo "rpcuser=$USER" >> ~/.zcash/zcash.conf
echo "rpcpassword=$PASSWORD" >> ~/.zcash/zcash.conf
echo 'equihashsolver=tromp' >> ~/.zcash/zcash.conf

exec /usr/bin/zcashd -mineraddress=$DEST -minetolocalwallet=0 -showmetrics=1  -disablewallet
